local function returncurrentgame(pid)
    if pid == 914010731 then
        return "rg"
    elseif pid == 863266079 or pid == 93911318070665 then
        return "ar2"
    elseif pid == 4991214437 then
        return "town"
    elseif pid == 10165583746 then
        return "exam"
    elseif pid == 443406476 then
        return "plazarus"
    elseif pid == 155615604 then
        return "prisonlife"
    end
end

return returncurrentgame
